version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: questly-app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - questly-network
        ports:
            - "9000:9000"

    nginx:
        image: nginx:alpine
        container_name: questly-nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        networks:
            - questly-network
        depends_on:
            - app

networks:
    questly-network:
        driver: bridge
